spring:
  application:
    name: hotel-restaurante-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:troque-esta-chave-em-producao-com-no-minimo-32-caracteres}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:120}
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/hotel-restaurante}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:hx1232}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    baseline-version: "0"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Africa/Maputo

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  jackson:
    time-zone: Africa/Maputo

logging:
  level:
    org.hibernate.SQL: warn

